# Generated by Django 2.2.6 on 2019-12-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of book', max_length=600, unique=True)),
                ('author', models.CharField(help_text='Author of book', max_length=600, unique=True)),
                ('genre', models.CharField(help_text='Book genre', max_length=600)),
                ('slug', models.CharField(blank=True, editable=False, help_text='Unique URL path to access this page. Generated by the system.', max_length=600)),
                ('synopsis', models.TextField(help_text='Write the content of your page here.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time this page was created. Automatically generated when the model saves.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this page was updated. Automatically generated when the model updates.')),
            ],
        ),
    ]
